# Site settings
title: Acme Air
description: > # this means to ignore newlines until "baseurl:"
    The sample application of a fictitious airline called Acme Air. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  acmeair

# Build settings
markdown: kramdown
